version: '3'

tasks:
  build:
    cmds:
      - go build

  generate:
    deps:
      - build
    cmds:
      - ./website

  serve:
    deps:
      - generate
    cmds:
      - caddy file-server --root ./docs --listen :8080
